### ISSUE TITLE
bioblend: Internal Server Error

### ISSUE THREAD

**Issue by hechth** [CESNET/usegalaxy#26]
Hi, I'm trying to get info on a workflow invocation step (so that I can automatically re-run all failed jobs from a step) using bioblend.

Unfortunately I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/hechth/dev/specdatri/resume_workflow_jobs.py", line 16, in <module>
    step = wf.show_invocation_step(wf_id, invocation_id, "55639049d2587598")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hechth/micromamba/envs/bioblend/lib/python3.12/site-packages/bioblend/galaxy/workflows/__init__.py", line 629, in show_invocation_step
    return self._get(url=url)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hechth/micromamba/envs/bioblend/lib/python3.12/site-packages/bioblend/galaxy/client.py", line 134, in _get
    raise ConnectionError(
bioblend.ConnectionError: GET: error 500: b'Internal Server Error', 0 attempts left: Internal Server Error
```

Any idea what this could be related to?

**Comment by martindemko** [comment]
Hi,
yesterday I saw a weird network behaviour when I tried to access the interface. It could be connected. But today it looks good. At leat from my perspective. How many times did you try? Could you try again in 10 or 30 min? If the trouble persists?
Thanks

**Comment by hechth** [comment]
Still the same error.

**Comment by hechth** [comment]
```
2024-12-03 1356.16.161459
Traceback (most recent call last):
  File "/home/hechth/dev/specdatri/resume_workflow_jobs.py", line 16, in <module>
    step = wf.show_invocation_step(wf_id, invocation_id, "55639049d2587598")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hechth/micromamba/envs/bioblend/lib/python3.12/site-packages/bioblend/galaxy/workflows/__init__.py", line 629, in show_invocation_step
    return self._get(url=url)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hechth/micromamba/envs/bioblend/lib/python3.12/site-packages/bioblend/galaxy/client.py", line 134, in _get
    raise ConnectionError(
bioblend.ConnectionError: GET: error 500: b'Internal Server Error', 0 attempts left: Internal Server Error
```

**Comment by martindemko** [comment]
I believe that your bioblend version is not compatible with our API, because what your code calls is actually this: 
/api/workflows/8beeeb724b45ff06/invocations/8bc463fd51e0b733/steps/55639049d2587598
and what works is this:
/api/workflows/8beeeb724b45ff06/invocations/8bc463fd51e0b733
I can see that step there in the list of steps, but I'm afraid that's not the proper API call to get access to that step. Could you please tell me the bioblend version you are using, please? Thanks

**Comment by hechth** [comment]
so the substeps are not supported?

I'm using bioblend version 1.4.0

**Comment by martenson** [comment]
@hechth please provide us with the script/step that is failing (together with versions of your bioblend etc.) so we can investiate

**Comment by hechth** [comment]
Seems like those scripts disappeared with my old laptop - anyways, not sure if this is important. In case I would need it again, I will just replicate it.
